### ISSUE TITLE
The Gauge.CSharp.Lib 0.8.0 is now targetting <TargetFramework>netcoreapp3.0</TargetFramework>

### ISSUE THREAD

**Issue by nablik** [getgauge/gauge-csharp-lib#15]
I don't know if this is a bug. But moving from .netstandard 2.1 to .netcore is quite a deal. 
Is there a good reason to such change (PS all my gauge frameworks are .netsatndard): there is nothing in the Readme that explain such architectural change. 
Second point important, if in case there is a clear explanaintion to such change, why not .netCore3.1 ? the 3.0 reached end of life last march and the 3.1 is the LTS version. 
Any explannation is more than welcome.

**Comment by sriv** [comment]
Thanks for bringing this up.

IIRC we had to do this because of some dependency in the tests. We'll investigate this.

In general, we prefer to keep the projects (at least the libs) to target standards. We were more religious about this when we had both gauge-dotnet and gauge-csharp (which was supporting .NET framework). 

And agree with you on using netcoreapp3.1 if we had to choose the application target framework.

**Comment by nablik** [comment]
Thanks @sriv 
Don't know if this could help. but I am using XUnit - .netcore 3.1.x and the library is .netstandard 2.1. 
they perfectly live side by side.

**Comment by nablik** [comment]
Just for your information: 
I have downloaded the code, change it to netstandard2.1 
![image](https://user-images.githubusercontent.com/11925279/95742626-32a9b380-0c88-11eb-9b0e-c2bddde2c8e3.png)
the tests are green, 
and build, test package works fine and produces the nuget package. 
![image](https://user-images.githubusercontent.com/11925279/95742863-a350d000-0c88-11eb-8132-6b7a3ffec853.png)

**Comment by nablik** [comment]
Will be fixed next release.
